In [ ]:
import numpy as np
a1 = list(range(1000000))
a2 = list(range(1000000, 2000000))
n1 = np.array(a1)
n2 = np.array(a2)

In [ ]:
%time
res = 0
for e, e2 in zip(a1, a2):
  res += (e * e2)
res

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.48 µs


833332333333500000

In [ ]:
%time
np.dot(n1, n2)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 8.11 µs


np.int64(833332333333500000)

In [ ]:
MultiDimArray = np.array([[73, 67, 43],
                          [91, 88, 64],
                          [87, 134, 58],
                          [102, 43, 37],
                          [69, 96, 70]])

In [ ]:
MultiDimArray

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [ ]:
MultiDimArray.shape

(5, 3)

In [ ]:
MultiDimArray = np.array([[[73, 67, 43]],
                          [[91, 88, 64]],
                          [[87, 134, 58]],
                          [[102, 43, 37]],
                          [[69, 96, 70]]])
MultiDimArray.shape

(5, 1, 3)

In [ ]:
MultiDimArray.dtype

dtype('int64')

When one element in the np array is a float then every other element becomes a float.

In [ ]:
array = np.array([[73, 67], [43, 7.0]])
array.dtype

dtype('float64')

In [ ]:
array

array([[73., 67.],
       [43.,  7.]])

In [ ]:
weights = np.array([0.3, 0.2, 0.5])
MultiDimArray @ weights

array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [ ]:
np.matmul(MultiDimArray, weights)


array([[56.8],
       [76.9],
       [81.9],
       [57.7],
       [74.9]])

In [ ]:
import urllib.request
# The link does not work
urllib.request.urlretrieve('https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 'climate.txt')


URLError: <urlopen error [Errno -2] Name or service not known>

In [ ]:
arr2 = np.array([[1,2,3], [1,2,3], [1,2,3]])
np.concatenate((arr2, weights.reshape(weights.shape[0], 1)), axis=1)

array([[1. , 2. , 3. , 0.3],
       [1. , 2. , 3. , 0.2],
       [1. , 2. , 3. , 0.5]])

In [ ]:
arr3 = np.array([[2],[3],[4]])
arr2 + arr3

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [ ]:
arr4 = np.array([[1,3,2], [1,2,3], [4,5,6]])
arr4 == arr2

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
arr4 >= arr2

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
arr4 <= arr2

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
arr4 < arr2

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [ ]:
(arr4 == arr2).sum()

np.int64(4)

In [ ]:
arr5 = np.array([[1, 2, 3]])
(arr5 == arr2).sum()

np.int64(9)

In [ ]:
arr5 = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]], [[17,18,19,20],[21,22,23,24]]])
arr5.shape

(3, 2, 4)

In [ ]:
arr5[0,1,3]

np.int64(8)

In [ ]:
arr5[1:]

array([[[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
arr5[1:, 0:1]

array([[[ 9, 10, 11, 12]],

       [[17, 18, 19, 20]]])

In [ ]:
arr5[1:, 0:1, :2]

array([[[ 9, 10]],

       [[17, 18]]])

In [ ]:
arr5[1:, 0:1, :2].shape

(2, 1, 2)

In [ ]:
arr5[1:, 0, 3]

array([12, 20])

In [ ]:
arr5[1, :1, :3]

array([[ 9, 10, 11]])

In [ ]:
arr5[:1, 0, :3]

array([[1, 2, 3]])

In [ ]:
arr5[0, 0, :3]

array([1, 2, 3])

In [ ]:
arr5[::2, 0::2, 0::2]

array([[[ 1,  3]],

       [[17, 19]]])

In [ ]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones([3,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones((4))

array([1., 1., 1., 1.])

In [ ]:
#identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#The rand picks a number from 0(inclusive) to 1(exclusive)
np.random.rand(3)

array([0.37044266, 0.03324095, 0.53486625])

In [ ]:
#The randn picks values using Gaussian distrubution so from -2 to 2 but might change based on how big you array is
np.random.randn(3,3)

array([[-1.73025718, -1.00596764, -1.83241287],
       [ 0.02357022, -0.55739578, -0.26887618],
       [ 1.28950683,  0.07204443,  0.16891032]])

In [ ]:
np.full([2,3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(0, 11, 2).reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
# The -1 in reshape means numpy will figure out how many columns based on how many rows we gave it
np.arange(0, 11, 2).reshape(3, -1)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
np.arange(0, 11, 2).reshape(3, 2, 1)

array([[[ 0],
        [ 2]],

       [[ 4],
        [ 6]],

       [[ 8],
        [10]]])

In [ ]:
np.arange(0, 11, 2).reshape(3, 2, -1)

array([[[ 0],
        [ 2]],

       [[ 4],
        [ 6]],

       [[ 8],
        [10]]])

In [ ]:
np.linspace(10, 20, 3)

array([10., 15., 20.])

Interacting with the OS and filesystem

In [ ]:
import os

In [ ]:
os.getcwd() # Shows what directory you are currently in

'/content'

In [ ]:
help(os.listdir)

Help on built-in function listdir in module posix:

listdir(path=None)
    Return a list containing the names of the files in the directory.
    
    path can be specified as either str, bytes, or a path-like object.  If path is bytes,
      the filenames returned will also be bytes; in all other circumstances
      the filenames returned will be str.
    If path is None, uses the path='.'.
    On some platforms, path may also be specified as an open file descriptor;\
      the file descriptor must refer to a directory.
      If this functionality is unavailable, using it raises NotImplementedError.
    
    The list is in arbitrary order.  It does not include the special
    entries '.' and '..' even if they are present in the directory.



In [ ]:
os.listdir('.') # The relative path or current path files

['.config',
 'result.csv',
 'drive',
 'italy-covid-daywise.csv',
 'locations.csv',
 'sample_data']

In [ ]:
os.listdir('/usr') # This is absolute path (when you know the path and want to know the files in it use this)

['lib32',
 'libexec',
 'libx32',
 'sbin',
 'include',
 'lib',
 'bin',
 'lib64',
 'share',
 'local',
 'games',
 'src',
 'colab',
 'grte']

In [ ]:
# Use this to create directories
os.makedirs("./data", exist_ok=True)

In [ ]:
'data' in os.listdir()

True

In [ ]:
os.listdir("./data")

[]

In [ ]:
# This works but when you try reading the csv it will cause an error due to parsing errors which is why you can just download the csv file directly
from urllib.request import urlretrieve
urlretrieve("https://github.com/Himanshutiwari15/data-analysis-visualisation/blob/main/italy-covid-daywise.csv", "italy-covid-daywise.csv")

('italy-covid-daywise.csv', <http.client.HTTPMessage at 0x79b2981a4e50>)